name = "tripverse-web"
pages_build_output_dir = ".open-next"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
NEXTJS_ENV = "production"
NEXT_PUBLIC_SUPABASE_URL = "https://xacebfrqlylphqjvlcec.supabase.co"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "sb_publishable_rLXwWtdC7I_moeL3AW2mmQ_483cCqVd"
